services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    platform: linux/amd64
    depends_on:
      - db
    build:
      context: .
      dockerfile_inline: |
        FROM wordpress:latest

        # Install additional packages
        RUN apt-get update && apt-get install -y \
            git \
            subversion \
            wget \
            unzip \
            vim \
            && rm -rf /var/lib/apt/lists/*

        # Install WP-CLI
        RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
            && chmod +x wp-cli.phar \
            && mv wp-cli.phar /usr/local/bin/wp

        # Install Composer
        RUN curl -sS https://getcomposer.org/installer | php \
            && mv composer.phar /usr/local/bin/composer

        # Install PHPUnit
        RUN composer global require phpunit/phpunit:^7.5 --no-interaction \
            && ln -s /root/.composer/vendor/bin/phpunit /usr/local/bin/phpunit

        # Set up WordPress test suite
        RUN mkdir -p /tmp/wordpress-tests-lib \
            && cd /tmp \
            && wget -nv -O wordpress-develop.zip https://github.com/WordPress/wordpress-develop/archive/trunk.zip \
            && unzip -q wordpress-develop.zip \
            && mv wordpress-develop-trunk/tests/phpunit /tmp/wordpress-tests-lib/ \
            && mv wordpress-develop-trunk/wp-tests-config-sample.php /tmp/wordpress-tests-lib/wp-tests-config.php \
            && rm -rf wordpress-develop-trunk wordpress-develop.zip

        # Configure test database
        RUN sed -i "s/youremptytestdbnamehere/wordpress_test/g" /tmp/wordpress-tests-lib/wp-tests-config.php \
            && sed -i "s/yourusernamehere/wordpress/g" /tmp/wordpress-tests-lib/wp-tests-config.php \
            && sed -i "s/yourpasswordhere/wordpress/g" /tmp/wordpress-tests-lib/wp-tests-config.php \
            && sed -i "s|localhost|db|g" /tmp/wordpress-tests-lib/wp-tests-config.php

        # Set environment variable for tests
        ENV WP_TESTS_DIR=/tmp/wordpress-tests-lib

    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_DEBUG_LOG: 'true'
      WORDPRESS_DEBUG_DISPLAY: 'false'
      WP_TESTS_DIR: /tmp/wordpress-tests-lib
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./tests:/tests
    command: >
      bash -c " # Wait for database while ! mysqladmin ping -h db --silent; do
        sleep 1
      done

      # Create test database if it doesn't exist mysql -h db -u wordpress -pwordpress -e 'CREATE DATABASE IF NOT EXISTS wordpress_test;' || true

      # Continue with normal WordPress startup docker-entrypoint.sh apache2-foreground "

  # Optional: PHPMyAdmin for database management
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    restart: always

volumes:
  db_data:
